### ISSUE TITLE
adal.NewServicePrincipalToken fails when PublicCloud.KeyVaultEndpoint is used as scope

### ISSUE THREAD

**Issue by shhsu** [Azure/go-autorest#164] opened 2017-08-23 00:15 UTC
Hi azure sdk team

I found an issue when using the keyvault client. I created a service principal with this line
```
spToken, err := adal.NewServicePrincipalToken(*oauthConfig, sp.ID, sp.Password, env.KeyVaultEndpoint)
```
Note that when `env` is `PublicCloud`, it would resolve to `https://vault.azure.net/`
https://github.com/Azure/go-autorest/blob/58f6f26e200fa5dfb40c9cd1c83f3e2c860d779d/autorest/azure/environments.go#L46

The back slash at the end of the URL is causing trouble and will cause an error like this when the code is run
```
keyvault.ManagementClient#GetKey: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF
```

Removing the back slash as the end like this `https://vault.azure.net` works

**Comment by marstr** [comment] 2017-08-23 03:06
Howdy @shhsu,

Thanks for pointing this out. This is a annoying problem that keeps popping up. However, I believe your issue is a duplicate of #145. I'm going to close it out as a duplicate for now, but if you feel there is something that I'm missing please feel free to mention me and tell me to open this back up.

-Martin

**Closed by marstr** 2017-08-23 03:06 UTC
Labels: duplicate
