### ISSUE TITLE
ECONNRESET on read is not a transient network error

### ISSUE THREAD

**Issue by mgaurav** [Azure/go-autorest#450] opened 2019-08-14 05:45 UTC
In DoRetryWithStatusCodes, we retry for a list of status codes and also retry on temporary network errors. However, I am seeing transient network errors not being retried.

E.g.
`compute.DisksClient#List: Failure sending request: StatusCode=0 -- Original Error: Get https://management.azure.com/subscriptions/13979c32-3382-46f7-8f3a-ef86b8270227/providers/Microsoft.Compute/disks?api-version=2018-09-30: read tcp 10.28.1.65:56094-u003e13.91.242.34:443: read: connection reset by peer`

It looks to me that "connection reset by peer" error is not treated as temporary by `IsTemporaryNetworkError`. Is there anyway I can enable retry on it for all autorest call (other than doing it in my application code itself)?

**Comment by jhendrixMSFT** [comment] 2019-08-14 21:45
I dug into this, the behavior is by design; i.e. the standard library doesn't treat ECONNRESET as a transient network error, see test `TestNotTemporaryRead` in [net_test.go](https://golang.org/src/net/net_test.go).  Do you know why the connection is being reset and does retrying resolve the issue?  I'm hesitant to treat this case as transient if the standard library doesn't (presumably they have a good reason).

**Comment by tombuildsstuff** [comment] 2019-08-15 08:26
@jhendrixMSFT 

> Do you know why the connection is being reset and does retrying resolve the issue?

FWIW we also see this through our test suite most days across a random selection of tests, presumably because of networking issues between AWS (where our CI runs) and Azure (where the ARM API's are)

**Comment by mgaurav** [comment] 2019-08-15 08:32
Thanks for looking. I am not sure why connection is being reset by Azure as there is no other information in the error logs. Retries fixes this issue, I suspect it might have to do with the load on the server side leading to connection being reset or transient network issue between application and Azure servers.

**Comment by mgaurav** [comment] 2019-08-15 10:08
azure-storage-node API also seem to treat ECONNRESET as retryable error: https://github.com/Azure/azure-storage-node/blob/master/ChangeLog.md

> ECONNRESET is handled in the retry policy filter.

> Fixed an issue which prevented transient server errors like ECONNRESET, ESOCKETTIMEDOUT and ETIMEDOUT from being retried.

**Comment by jhendrixMSFT** [comment] 2019-08-15 14:01
Thanks for the info, I will update the retry logic to include these conditions.

**Comment by jhendrixMSFT** [comment] 2019-08-21 18:01
I have a tentative fix here https://github.com/Azure/go-autorest/issues/450.  Would one of you be able to try it out?  I don't have a repro of this issue so had to simulate it via the test in net_test.go cited above.

**Comment by kahing** [comment] 2019-08-22 04:25
I just hit this and tried to dump `autorest.DetailedError.Original`:

```
*url.Error: Delete [secure]goofys-test-dkwipl51mu9uwhqb/test_dir%2F1%2F7%2F5: read tcp 10.20.0.8:49214->52.239.193.98:443: read: connection reset by peer
```

I wonder if it's sufficient to amend the check for `net.Error` with this since `url.Error` has https://golang.org/pkg/net/url/#Error.Temporary

**Comment by jhendrixMSFT** [comment] 2019-08-22 14:53
We do this already in `internal.IsTemporaryNetworkError()`, the problem is that the standard lib doesn't treat ECONNRESET as a temporary error (see above discussion).

**Comment by mgaurav** [comment] 2019-09-02 08:42
@jhendrixMSFT I tried to reproduce it in a test environment, but haven't been able to reproduce it. I have only seen it in production, so unable to verify the fix.

**Comment by tombuildsstuff** [comment] 2019-09-02 08:50
@jhendrixMSFT I'm going to try and run our test suite with this patch at some point this week, which should confirm this one way or the other :)

**Comment by jhendrixMSFT** [comment] 2019-09-03 18:30
@mgaurav no worries I appreciate the help.
@tombuildsstuff thanks for jumping in :)

**Comment by mgaurav** [comment] 2019-09-28 05:26
@jhendrixMSFT When do you plan to release this change? I would like to incorporate it in our production.

**Comment by jhendrixMSFT** [comment] 2019-09-30 15:18
@mgaurav still iterating on the fix, see the PR for the latest comments.

**Comment by jhendrixMSFT** [comment] 2019-10-07 21:39
Fixed in https://github.com/Azure/go-autorest/releases/tag/v13.0.2

**Closed by jhendrixMSFT** 2019-10-07 21:39 UTC
