### ISSUE TITLE
Having the API version in authentication URLs breaks bearer token for ADAL

### ISSUE THREAD

**Issue by radu-matei** [Azure/go-autorest#321] opened 2018-09-13 01:52 UTC
Because of the inclusion of the API version in the URLs for authorization, token and device code, the format of the returned token is not compatible with what AAD accepts for a bearer.

Specifically, the same issue as in the Node library (https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/issues/128) and Python (https://github.com/AzureAD/azure-activedirectory-library-for-python/pull/57) 

The returned JWT token has the audience format as `aud: "spn:{APPLICATION_ID}"` - notice the additional `spn:`, which is missing when manually generating a token.

Not really sure how a fix would look like so that backwards compatibility is maintained for existing users (the Python library simply introduced an `api_version`  parameter), but in its current form, it is impossible to generate a functional token - and the main issue here is that the library itself thinks it generated a successful token, but that cannot be correctly consumed by an AAD application.

Full diff for the change (`autorest/adal/config.go`):

```
@@ -50,7 +50,7 @@ func NewOAuthConfig(activeDirectoryEndpoint, tenantID string) (*OAuthConfig, err
                return nil, err
        }
        // it's legal for tenantID to be empty so don't validate it
-       const activeDirectoryEndpointTemplate = "%s/oauth2/%s?api-version=%s"
+       const activeDirectoryEndpointTemplate = "%s/oauth2/%s"
        u, err := url.Parse(activeDirectoryEndpoint)
        if err != nil {
                return nil, err
@@ -59,15 +59,15 @@ func NewOAuthConfig(activeDirectoryEndpoint, tenantID string) (*OAuthConfig, err
        if err != nil {
                return nil, err
        }
-       authorizeURL, err := u.Parse(fmt.Sprintf(activeDirectoryEndpointTemplate, tenantID, "authorize", activeDirectoryAPIVersion))
+       authorizeURL, err := u.Parse(fmt.Sprintf(activeDirectoryEndpointTemplate, tenantID, "authorize"))
        if err != nil {
                return nil, err
        }
-       tokenURL, err := u.Parse(fmt.Sprintf(activeDirectoryEndpointTemplate, tenantID, "token", activeDirectoryAPIVersion))
+       tokenURL, err := u.Parse(fmt.Sprintf(activeDirectoryEndpointTemplate, tenantID, "token"))
        if err != nil {
                return nil, err
        }
-       deviceCodeURL, err := u.Parse(fmt.Sprintf(activeDirectoryEndpointTemplate, tenantID, "devicecode", activeDirectoryAPIVersion))
+       deviceCodeURL, err := u.Parse(fmt.Sprintf(activeDirectoryEndpointTemplate, tenantID, "devicecode"))
        if err != nil {
                return nil, err
        }
```

**Comment by vladbarosan** [comment] 2018-09-14 19:07
Hi @radu-matei this seems a duplicate of https://github.com/Azure/go-autorest/issues/277 which was proposing something similar and was closed which was closed in favor of https://github.com/Azure/go-autorest/issues/133

**Comment by vladbarosan** [comment] 2018-09-14 19:08
@joshgav is there anything we want to reconsider here or close it in favor of #133 as the previous one was

**Comment by jhendrixMSFT** [comment] 2018-10-05 20:43
Fixed in https://github.com/Azure/go-autorest/releases/tag/v11.1.0

**Closed by jhendrixMSFT** 2018-10-05 20:43 UTC
